name: CICD Pipeline for deploying AWS Resources
run-name: ${{ github.actor }} has triggered the workflow

on:
  push:
    branches:
      - 'main'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_subscriber_email_addresses: '["${{ secrets.SUBSCRIBER_EMAILS }}"]'

jobs:
  deploy-backend:
    name: Deploy Budget
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: ./environment/production

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./environment/production

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./environment/production

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./environment/production
